language: cpp

os:
  - linux
  - osx

env:
  - variant=test_debug cc=gcc-cpp11 sim=1
  - variant=test_debug cc=clang-cpp11 sim=0
  - variant=test_debug cc=gcc-cpp98 sim=0
  - variant=test_release cc=gcc-cpp11 sim=0
  - variant=test_barebones cc=gcc-cpp11 sim=0

git:
  submodules: false

# container-based builds
sudo: false
cache:
  directories:
    - $HOME/.ccache

# sources  list: https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json,
# packages list: https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - libboost1.55-all-dev
    - libboost1.55-tools-dev
    - python2.7-dev
    - g++-4.8

before_install:
  - git submodule update --init --recursive

install:
  - 'echo "using gcc : cpp11 : ccache g++-4.8 : <cflags>-std=c11 <cxxflags>-std=c++11 ;" > ~/user-config.jam'
  - 'echo "using gcc : cpp98 : ccache g++-4.8 : <cflags>-std=c99 <cxxflags>-std=c++98 ;" >> ~/user-config.jam'
  - 'echo "using clang : cpp11 : ccache clang++ : <cflags>-std=c11 <cxxflags>-std=c++11 ;" >> ~/user-config.jam'
  - 'echo "using clang : cpp98 : ccache clang++ : <cflags>-std=c99 <cxxflags>-std=c++98 ;" >> ~/user-config.jam'
  - 'echo "using python : 2.7 ;" >> ~/user-config.jam'
  - ccache -V && ccache --show-stats && ccache --zero-stats

script:
  - cd test
  - bjam --hash -j3 warnings-as-errors=on variant=$variant -l900 $CC
  - cd ../examples
  - bjam --hash -j3 warnings-as-errors=on variant=$variant $CC
  - cd ../bindings/python
  - bjam --hash -j3 warnings-as-errors=on variant=$variant $CC stage_module
  - LD_LIBRARY_PATH=. python test.py
  - if [ $sim ]; then
    cd ../../simulation;
    bjam --hash -j3 crypto=built-in $CC;
    fi
  - ccache --show-stats

