version: 1.0.{build}
branches:
  only:
  - master
os: Visual Studio 2015
clone_depth: 1
environment:
  matrix:
  - variant: test_debug
    compiler: msvc-12.0
    linkflags: '"/LIBPATH:C:\\OpenSSL-Win32\\lib"'
  - variant: test_debug
    compiler: msvc-10.0
    linkflags: '"/LIBPATH:C:\\OpenSSL-Win32\\lib"'
  - variant: test_debug
    compiler: msvc-14.0
    linkflags: '"/LIBPATH:C:\\OpenSSL-Win32\\lib"'
  - variant: test_barebones
    compiler: msvc-12.0
    linkflags: '"/LIBPATH:C:\\OpenSSL-Win32\\lib"'
  - variant: test_release
    compiler: msvc-12.0
    linkflags: '"/LIBPATH:C:\\OpenSSL-Win32\\lib"'

# mingw and boost.random don't like each other. Comment this back in once there
# is support

#  - variant: test_debug
#    compiler: gcc
#    linkflags: '"-LC:\\OpenSSL-Win32\\lib"'

install:
- git submodule update --init --recursive
- set ROOT_DIRECTORY=%CD%
- cd %ROOT_DIRECTORY%
- if not exist c:\OpenSSL-Win32\nul (
  appveyor DownloadFile https://strcpy.net/packages/Win32OpenSSL-1_0_2a.exe
  && Win32OpenSSL-1_0_2a.exe /silent /verysilent /sp- /suppressmsgboxes )
- copy c:\OpenSSL-Win32\ssleay32.dll %WINDIR%\system32
- copy c:\OpenSSL-Win32\libeay32.dll %WINDIR%\system32
- cd %ROOT_DIRECTORY%
- set BOOST_ROOT=c:\Libraries\boost
- set BOOST_BUILD_PATH=%BOOST_ROOT%\tools\build
- echo %BOOST_ROOT%
- echo %BOOST_BUILD_PATH%
- set PATH=%PATH%;%BOOST_BUILD_PATH%\src\engine\bin.ntx86
- 'echo using msvc : 10.0 ; >%HOMEDRIVE%%HOMEPATH%\user-config.jam'
- 'echo using msvc : 12.0 ; >>%HOMEDRIVE%%HOMEPATH%\user-config.jam'
- 'echo using msvc : 14.0 ; >>%HOMEDRIVE%%HOMEPATH%\user-config.jam'
- echo using gcc ; >>%HOMEDRIVE%%HOMEPATH%\user-config.jam
- type %HOMEDRIVE%%HOMEPATH%\user-config.jam
- cd %ROOT_DIRECTORY%
- set PATH=%PATH%;c:\Mingw\bin
- g++ --version
- python --version
- echo %ROOT_DIRECTORY%
cache:
- C:\OpenSSL-Win32
build_script:
- cd %ROOT_DIRECTORY%\examples
- b2.exe --hash -j2 %compiler% variant=%variant% linkflags=%linkflags% include="C:\\OpenSSL-Win32\\include"
- cd %ROOT_DIRECTORY%\test
- b2.exe --hash -j2 address-model=32 win-tests %compiler% variant=%variant% link=shared linkflags=%linkflags% include="C:\\OpenSSL-Win32\\include"
- cd %ROOT_DIRECTORY%\bindings\python
- b2.exe --hash -j2 %compiler% variant=%variant% linkflags=%linkflags% include="C:\\OpenSSL-Win32\\include" stage_module
- python test.py
- if %variant% == "test_debug" (
  cd %ROOT_DIRECTORY%\simulation
  && b2.exe --hash -j2 crypto=built-in %compiler% )

